/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type OrderId = bigint;
export interface ExchangeRate {
    usdToEur: number;
    eurToUsd: number;
}
export type RestaurantIdentityId = string;
export interface OrderItem {
    componentId: ComponentId;
    quantity: bigint;
    category: EmployeeCategory;
    menuItemId: MenuItemId;
}
export interface AccessCodeData {
    expiresAt?: bigint;
    code: AccessCode;
    createdAt: bigint;
    role: UserRole;
    isActive: boolean;
    restaurantId?: RestaurantId;
    employeeId?: EmployeeId;
}
export type RestaurantId = string;
export interface Restaurant {
    id: RestaurantId;
    manager: Principal;
    name: string;
    components: Array<Component>;
    description: string;
    tables: Array<Table>;
    address: string;
    defaultCurrency: Currency;
    identityId: RestaurantIdentityId;
    colorScheme: ColorScheme;
}
export interface Component {
    id: ComponentId;
    name: string;
    description: string;
}
export interface MenuItem {
    id: MenuItemId;
    name: string;
    routedBy: EmployeeCategory;
    description: string;
    componentId: ComponentId;
    category: string;
    price: bigint;
}
export type MenuItemId = string;
export type CanisterId = string;
export type EmployeeId = string;
export interface Table {
    id: TableId;
    customerLink: string;
    active: boolean;
    name: string;
    location: string;
}
export interface ColorScheme {
    primaryColor: string;
    accentColor: string;
    secondaryColor: string;
}
export type AccessCode = string;
export interface Employee {
    id: EmployeeId;
    principal?: Principal;
    name: string;
    role: EmployeeRole;
    accessCode: AccessCode;
}
export type TableId = string;
export type ComponentId = string;
export interface UserProfile {
    name: string;
}
export interface OrderBatch {
    id: OrderId;
    status: OrderStatus;
    source: OrderSource;
    toLabel: string;
    tableId: TableId;
    restaurantId: RestaurantId;
    currency: Currency;
    timestamp: bigint;
    customerId?: Principal;
    items: Array<OrderItem>;
}
export enum Currency {
    eur = "eur",
    usd = "usd"
}
export enum EmployeeRole {
    bar = "bar",
    kitchen = "kitchen",
    waiter = "waiter"
}
export enum OrderSource {
    bar = "bar",
    table = "table",
    kitchen = "kitchen"
}
export enum OrderStatus {
    paid = "paid",
    ordered = "ordered",
    readyToServe = "readyToServe",
    toBePaid = "toBePaid"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addEmployee(restaurantId: RestaurantId, employee: Employee): Promise<void>;
    addMenuItem(restaurantId: RestaurantId, menuItem: MenuItem): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRestaurantToCanister(restaurantId: RestaurantId, canisterId: CanisterId): Promise<void>;
    checkEmployeeLink(principal: Principal, restaurantIdentityId: RestaurantIdentityId): Promise<EmployeeId | null>;
    claimAccessCode(code: AccessCode, restaurantIdentityId: RestaurantIdentityId): Promise<void>;
    createRestaurant(restaurant: Restaurant): Promise<void>;
    deactivateAccessCode(code: AccessCode): Promise<void>;
    deleteEmployee(restaurantId: RestaurantId, employeeId: EmployeeId): Promise<void>;
    deleteMenuItem(restaurantId: RestaurantId, menuItemId: MenuItemId): Promise<void>;
    deleteTable(restaurantId: RestaurantId, tableId: TableId): Promise<void>;
    generateAccessCode(role: UserRole, restaurantId: RestaurantId | null, employeeId: EmployeeId | null): Promise<AccessCode>;
    getAccessCodesByRestaurant(restaurantId: RestaurantId): Promise<Array<AccessCodeData>>;
    getAllRestaurants(): Promise<Array<Restaurant>>;
    getAvailableAccessCodes(identityId: RestaurantIdentityId): Promise<Array<AccessCode>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCanisterForRestaurant(restaurantId: RestaurantId): Promise<CanisterId | null>;
    getCustomerOrderHistory(): Promise<Array<OrderBatch>>;
    getEmployees(restaurantId: RestaurantId): Promise<Array<Employee>>;
    getExchangeRate(): Promise<ExchangeRate>;
    getMenuItems(restaurantId: RestaurantId): Promise<Array<MenuItem>>;
    getMenuItemsByCategory(restaurantId: RestaurantId): Promise<Array<[string, Array<MenuItem>]>>;
    getOrder(orderId: OrderId): Promise<OrderBatch | null>;
    getOrdersBySource(restaurantId: RestaurantId, source: OrderSource): Promise<Array<OrderBatch>>;
    getOrdersByStatus(restaurantId: RestaurantId, status: OrderStatus): Promise<Array<OrderBatch>>;
    getOrdersByStatusAndSource(restaurantId: RestaurantId, status: OrderStatus, source: OrderSource): Promise<Array<OrderBatch>>;
    getOrdersForRestaurant(restaurantId: RestaurantId): Promise<Array<OrderBatch>>;
    getOrdersForWaiter(restaurantId: RestaurantId): Promise<Array<OrderBatch>>;
    getRestaurant(restaurantId: RestaurantId): Promise<Restaurant | null>;
    getRestaurantByTableId(tableId: TableId): Promise<Restaurant | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getValidAccessCodesForRestaurant(restaurantId: RestaurantId): Promise<Array<AccessCodeData>>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    placeOrder(order: OrderBatch): Promise<OrderId>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setCustomAccessCode(restaurantId: RestaurantId, employeeId: EmployeeId, customCode: AccessCode): Promise<void>;
    updateAccessCode(code: AccessCode): Promise<AccessCode>;
    updateExchangeRate(newRate: ExchangeRate): Promise<void>;
    updateOrderStatus(orderId: OrderId, newStatus: OrderStatus): Promise<void>;
    updateRestaurant(restaurant: Restaurant): Promise<void>;
    validateRestaurantIdentityId(identityId: RestaurantIdentityId): Promise<boolean>;
    verifyAccessCode(code: AccessCode): Promise<{
        role?: UserRole;
        error: string;
        restaurantId?: RestaurantId;
        employeeId?: EmployeeId;
        isValid: boolean;
    }>;
}
import type { AccessCode as _AccessCode, AccessCodeData as _AccessCodeData, CanisterId as _CanisterId, ColorScheme as _ColorScheme, Component as _Component, ComponentId as _ComponentId, Currency as _Currency, Employee as _Employee, EmployeeCategory as _EmployeeCategory, EmployeeId as _EmployeeId, EmployeeRole as _EmployeeRole, MenuItem as _MenuItem, MenuItemId as _MenuItemId, OrderBatch as _OrderBatch, OrderId as _OrderId, OrderItem as _OrderItem, OrderSource as _OrderSource, OrderStatus as _OrderStatus, Restaurant as _Restaurant, RestaurantId as _RestaurantId, RestaurantIdentityId as _RestaurantIdentityId, Table as _Table, TableId as _TableId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addEmployee(arg0: RestaurantId, arg1: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmployee(arg0, to_candid_Employee_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmployee(arg0, to_candid_Employee_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async addMenuItem(arg0: RestaurantId, arg1: MenuItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(arg0, to_candid_MenuItem_n5(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(arg0, to_candid_MenuItem_n5(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async assignRestaurantToCanister(arg0: RestaurantId, arg1: CanisterId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRestaurantToCanister(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRestaurantToCanister(arg0, arg1);
            return result;
        }
    }
    async checkEmployeeLink(arg0: Principal, arg1: RestaurantIdentityId): Promise<EmployeeId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.checkEmployeeLink(arg0, arg1);
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkEmployeeLink(arg0, arg1);
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async claimAccessCode(arg0: AccessCode, arg1: RestaurantIdentityId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAccessCode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAccessCode(arg0, arg1);
            return result;
        }
    }
    async createRestaurant(arg0: Restaurant): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createRestaurant(to_candid_Restaurant_n11(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRestaurant(to_candid_Restaurant_n11(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async deactivateAccessCode(arg0: AccessCode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateAccessCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateAccessCode(arg0);
            return result;
        }
    }
    async deleteEmployee(arg0: RestaurantId, arg1: EmployeeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0, arg1);
            return result;
        }
    }
    async deleteMenuItem(arg0: RestaurantId, arg1: MenuItemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0, arg1);
            return result;
        }
    }
    async deleteTable(arg0: RestaurantId, arg1: TableId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTable(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTable(arg0, arg1);
            return result;
        }
    }
    async generateAccessCode(arg0: UserRole, arg1: RestaurantId | null, arg2: EmployeeId | null): Promise<AccessCode> {
        if (this.processError) {
            try {
                const result = await this.actor.generateAccessCode(to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg0), to_candid_opt_n15(this.uploadFile, this.downloadFile, arg1), to_candid_opt_n16(this.uploadFile, this.downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateAccessCode(to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg0), to_candid_opt_n15(this.uploadFile, this.downloadFile, arg1), to_candid_opt_n16(this.uploadFile, this.downloadFile, arg2));
            return result;
        }
    }
    async getAccessCodesByRestaurant(arg0: RestaurantId): Promise<Array<AccessCodeData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccessCodesByRestaurant(arg0);
                return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccessCodesByRestaurant(arg0);
            return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllRestaurants(): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRestaurants();
                return from_candid_vec_n24(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRestaurants();
            return from_candid_vec_n24(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAvailableAccessCodes(arg0: RestaurantIdentityId): Promise<Array<AccessCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableAccessCodes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableAccessCodes(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCanisterForRestaurant(arg0: RestaurantId): Promise<CanisterId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanisterForRestaurant(arg0);
                return from_candid_opt_n30(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanisterForRestaurant(arg0);
            return from_candid_opt_n30(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCustomerOrderHistory(): Promise<Array<OrderBatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerOrderHistory();
                return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerOrderHistory();
            return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async getEmployees(arg0: RestaurantId): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployees(arg0);
                return from_candid_vec_n44(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployees(arg0);
            return from_candid_vec_n44(this.uploadFile, this.downloadFile, result);
        }
    }
    async getExchangeRate(): Promise<ExchangeRate> {
        if (this.processError) {
            try {
                const result = await this.actor.getExchangeRate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExchangeRate();
            return result;
        }
    }
    async getMenuItems(arg0: RestaurantId): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItems(arg0);
                return from_candid_vec_n48(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItems(arg0);
            return from_candid_vec_n48(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMenuItemsByCategory(arg0: RestaurantId): Promise<Array<[string, Array<MenuItem>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItemsByCategory(arg0);
                return from_candid_vec_n51(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItemsByCategory(arg0);
            return from_candid_vec_n51(this.uploadFile, this.downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<OrderBatch | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n53(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n53(this.uploadFile, this.downloadFile, result);
        }
    }
    async getOrdersBySource(arg0: RestaurantId, arg1: OrderSource): Promise<Array<OrderBatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersBySource(arg0, to_candid_OrderSource_n54(this.uploadFile, this.downloadFile, arg1));
                return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersBySource(arg0, to_candid_OrderSource_n54(this.uploadFile, this.downloadFile, arg1));
            return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async getOrdersByStatus(arg0: RestaurantId, arg1: OrderStatus): Promise<Array<OrderBatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus(arg0, to_candid_OrderStatus_n56(this.uploadFile, this.downloadFile, arg1));
                return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus(arg0, to_candid_OrderStatus_n56(this.uploadFile, this.downloadFile, arg1));
            return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async getOrdersByStatusAndSource(arg0: RestaurantId, arg1: OrderStatus, arg2: OrderSource): Promise<Array<OrderBatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatusAndSource(arg0, to_candid_OrderStatus_n56(this.uploadFile, this.downloadFile, arg1), to_candid_OrderSource_n54(this.uploadFile, this.downloadFile, arg2));
                return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatusAndSource(arg0, to_candid_OrderStatus_n56(this.uploadFile, this.downloadFile, arg1), to_candid_OrderSource_n54(this.uploadFile, this.downloadFile, arg2));
            return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async getOrdersForRestaurant(arg0: RestaurantId): Promise<Array<OrderBatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersForRestaurant(arg0);
                return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersForRestaurant(arg0);
            return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async getOrdersForWaiter(arg0: RestaurantId): Promise<Array<OrderBatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersForWaiter(arg0);
                return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersForWaiter(arg0);
            return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRestaurant(arg0: RestaurantId): Promise<Restaurant | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurant(arg0);
                return from_candid_opt_n58(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurant(arg0);
            return from_candid_opt_n58(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRestaurantByTableId(arg0: TableId): Promise<Restaurant | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurantByTableId(arg0);
                return from_candid_opt_n58(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurantByTableId(arg0);
            return from_candid_opt_n58(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getValidAccessCodesForRestaurant(arg0: RestaurantId): Promise<Array<AccessCodeData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getValidAccessCodesForRestaurant(arg0);
                return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getValidAccessCodesForRestaurant(arg0);
            return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeOrder(arg0: OrderBatch): Promise<OrderId> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_OrderBatch_n59(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_OrderBatch_n59(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setCustomAccessCode(arg0: RestaurantId, arg1: EmployeeId, arg2: AccessCode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCustomAccessCode(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCustomAccessCode(arg0, arg1, arg2);
            return result;
        }
    }
    async updateAccessCode(arg0: AccessCode): Promise<AccessCode> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAccessCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAccessCode(arg0);
            return result;
        }
    }
    async updateExchangeRate(arg0: ExchangeRate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExchangeRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExchangeRate(arg0);
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n56(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n56(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async updateRestaurant(arg0: Restaurant): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRestaurant(to_candid_Restaurant_n11(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRestaurant(to_candid_Restaurant_n11(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async validateRestaurantIdentityId(arg0: RestaurantIdentityId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateRestaurantIdentityId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateRestaurantIdentityId(arg0);
            return result;
        }
    }
    async verifyAccessCode(arg0: AccessCode): Promise<{
        role?: UserRole;
        error: string;
        restaurantId?: RestaurantId;
        employeeId?: EmployeeId;
        isValid: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAccessCode(arg0);
                return from_candid_record_n64(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAccessCode(arg0);
            return from_candid_record_n64(this.uploadFile, this.downloadFile, result);
        }
    }
}
function from_candid_AccessCodeData_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccessCodeData): AccessCodeData {
    return from_candid_record_n19(uploadFile, downloadFile, value);
}
function from_candid_Currency_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Currency): Currency {
    return from_candid_variant_n28(uploadFile, downloadFile, value);
}
function from_candid_EmployeeCategory_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeCategory): EmployeeCategory {
    return from_candid_variant_n43(uploadFile, downloadFile, value);
}
function from_candid_EmployeeRole_n47(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeRole): EmployeeRole {
    return from_candid_variant_n43(uploadFile, downloadFile, value);
}
function from_candid_Employee_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Employee {
    return from_candid_record_n46(uploadFile, downloadFile, value);
}
function from_candid_MenuItem_n49(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItem): MenuItem {
    return from_candid_record_n50(uploadFile, downloadFile, value);
}
function from_candid_OrderBatch_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderBatch): OrderBatch {
    return from_candid_record_n33(uploadFile, downloadFile, value);
}
function from_candid_OrderItem_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderItem): OrderItem {
    return from_candid_record_n41(uploadFile, downloadFile, value);
}
function from_candid_OrderSource_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderSource): OrderSource {
    return from_candid_variant_n37(uploadFile, downloadFile, value);
}
function from_candid_OrderStatus_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n35(uploadFile, downloadFile, value);
}
function from_candid_Restaurant_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Restaurant): Restaurant {
    return from_candid_record_n26(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(uploadFile, downloadFile, value);
}
function from_candid_opt_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmployeeId]): EmployeeId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestaurantId]): RestaurantId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CanisterId]): CanisterId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n53(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrderBatch]): OrderBatch | null {
    return value.length === 0 ? null : from_candid_OrderBatch_n32(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n58(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Restaurant]): Restaurant | null {
    return value.length === 0 ? null : from_candid_Restaurant_n25(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n65(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserRole]): UserRole | null {
    return value.length === 0 ? null : from_candid_UserRole_n21(uploadFile, downloadFile, value[0]);
}
function from_candid_record_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiresAt: [] | [bigint];
    code: _AccessCode;
    createdAt: bigint;
    role: _UserRole;
    isActive: boolean;
    restaurantId: [] | [_RestaurantId];
    employeeId: [] | [_EmployeeId];
}): {
    expiresAt?: bigint;
    code: AccessCode;
    createdAt: bigint;
    role: UserRole;
    isActive: boolean;
    restaurantId?: RestaurantId;
    employeeId?: EmployeeId;
} {
    return {
        expiresAt: record_opt_to_undefined(from_candid_opt_n20(uploadFile, downloadFile, value.expiresAt)),
        code: value.code,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n21(uploadFile, downloadFile, value.role),
        isActive: value.isActive,
        restaurantId: record_opt_to_undefined(from_candid_opt_n23(uploadFile, downloadFile, value.restaurantId)),
        employeeId: record_opt_to_undefined(from_candid_opt_n10(uploadFile, downloadFile, value.employeeId))
    };
}
function from_candid_record_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RestaurantId;
    manager: Principal;
    name: string;
    components: Array<_Component>;
    description: string;
    tables: Array<_Table>;
    address: string;
    defaultCurrency: _Currency;
    identityId: _RestaurantIdentityId;
    colorScheme: _ColorScheme;
}): {
    id: RestaurantId;
    manager: Principal;
    name: string;
    components: Array<Component>;
    description: string;
    tables: Array<Table>;
    address: string;
    defaultCurrency: Currency;
    identityId: RestaurantIdentityId;
    colorScheme: ColorScheme;
} {
    return {
        id: value.id,
        manager: value.manager,
        name: value.name,
        components: value.components,
        description: value.description,
        tables: value.tables,
        address: value.address,
        defaultCurrency: from_candid_Currency_n27(uploadFile, downloadFile, value.defaultCurrency),
        identityId: value.identityId,
        colorScheme: value.colorScheme
    };
}
function from_candid_record_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    source: _OrderSource;
    toLabel: string;
    tableId: _TableId;
    restaurantId: _RestaurantId;
    currency: _Currency;
    timestamp: bigint;
    customerId: [] | [Principal];
    items: Array<_OrderItem>;
}): {
    id: OrderId;
    status: OrderStatus;
    source: OrderSource;
    toLabel: string;
    tableId: TableId;
    restaurantId: RestaurantId;
    currency: Currency;
    timestamp: bigint;
    customerId?: Principal;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n34(uploadFile, downloadFile, value.status),
        source: from_candid_OrderSource_n36(uploadFile, downloadFile, value.source),
        toLabel: value.toLabel,
        tableId: value.tableId,
        restaurantId: value.restaurantId,
        currency: from_candid_Currency_n27(uploadFile, downloadFile, value.currency),
        timestamp: value.timestamp,
        customerId: record_opt_to_undefined(from_candid_opt_n38(uploadFile, downloadFile, value.customerId)),
        items: from_candid_vec_n39(uploadFile, downloadFile, value.items)
    };
}
function from_candid_record_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    componentId: _ComponentId;
    quantity: bigint;
    category: _EmployeeCategory;
    menuItemId: _MenuItemId;
}): {
    componentId: ComponentId;
    quantity: bigint;
    category: EmployeeCategory;
    menuItemId: MenuItemId;
} {
    return {
        componentId: value.componentId,
        quantity: value.quantity,
        category: from_candid_EmployeeCategory_n42(uploadFile, downloadFile, value.category),
        menuItemId: value.menuItemId
    };
}
function from_candid_record_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EmployeeId;
    principal: [] | [Principal];
    name: string;
    role: _EmployeeRole;
    accessCode: _AccessCode;
}): {
    id: EmployeeId;
    principal?: Principal;
    name: string;
    role: EmployeeRole;
    accessCode: AccessCode;
} {
    return {
        id: value.id,
        principal: record_opt_to_undefined(from_candid_opt_n38(uploadFile, downloadFile, value.principal)),
        name: value.name,
        role: from_candid_EmployeeRole_n47(uploadFile, downloadFile, value.role),
        accessCode: value.accessCode
    };
}
function from_candid_record_n50(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MenuItemId;
    name: string;
    routedBy: _EmployeeCategory;
    description: string;
    componentId: _ComponentId;
    category: string;
    price: bigint;
}): {
    id: MenuItemId;
    name: string;
    routedBy: EmployeeCategory;
    description: string;
    componentId: ComponentId;
    category: string;
    price: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        routedBy: from_candid_EmployeeCategory_n42(uploadFile, downloadFile, value.routedBy),
        description: value.description,
        componentId: value.componentId,
        category: value.category,
        price: value.price
    };
}
function from_candid_record_n64(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: [] | [_UserRole];
    error: string;
    restaurantId: [] | [_RestaurantId];
    employeeId: [] | [_EmployeeId];
    isValid: boolean;
}): {
    role?: UserRole;
    error: string;
    restaurantId?: RestaurantId;
    employeeId?: EmployeeId;
    isValid: boolean;
} {
    return {
        role: record_opt_to_undefined(from_candid_opt_n65(uploadFile, downloadFile, value.role)),
        error: value.error,
        restaurantId: record_opt_to_undefined(from_candid_opt_n23(uploadFile, downloadFile, value.restaurantId)),
        employeeId: record_opt_to_undefined(from_candid_opt_n10(uploadFile, downloadFile, value.employeeId)),
        isValid: value.isValid
    };
}
function from_candid_tuple_n52(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, Array<_MenuItem>]): [string, Array<MenuItem>] {
    return [
        value[0],
        from_candid_vec_n48(uploadFile, downloadFile, value[1])
    ];
}
function from_candid_variant_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eur: null;
} | {
    usd: null;
}): Currency {
    return "eur" in value ? Currency.eur : "usd" in value ? Currency.usd : value;
}
function from_candid_variant_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    ordered: null;
} | {
    readyToServe: null;
} | {
    toBePaid: null;
}): OrderStatus {
    return "paid" in value ? OrderStatus.paid : "ordered" in value ? OrderStatus.ordered : "readyToServe" in value ? OrderStatus.readyToServe : "toBePaid" in value ? OrderStatus.toBePaid : value;
}
function from_candid_variant_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bar: null;
} | {
    table: null;
} | {
    kitchen: null;
}): OrderSource {
    return "bar" in value ? OrderSource.bar : "table" in value ? OrderSource.table : "kitchen" in value ? OrderSource.kitchen : value;
}
function from_candid_variant_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bar: null;
} | {
    kitchen: null;
} | {
    waiter: null;
}): EmployeeRole {
    return "bar" in value ? EmployeeRole.bar : "kitchen" in value ? EmployeeRole.kitchen : "waiter" in value ? EmployeeRole.waiter : value;
}
function from_candid_vec_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AccessCodeData>): Array<AccessCodeData> {
    return value.map((x)=>from_candid_AccessCodeData_n18(uploadFile, downloadFile, x));
}
function from_candid_vec_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Restaurant>): Array<Restaurant> {
    return value.map((x)=>from_candid_Restaurant_n25(uploadFile, downloadFile, x));
}
function from_candid_vec_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderBatch>): Array<OrderBatch> {
    return value.map((x)=>from_candid_OrderBatch_n32(uploadFile, downloadFile, x));
}
function from_candid_vec_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderItem>): Array<OrderItem> {
    return value.map((x)=>from_candid_OrderItem_n40(uploadFile, downloadFile, x));
}
function from_candid_vec_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Employee>): Array<Employee> {
    return value.map((x)=>from_candid_Employee_n45(uploadFile, downloadFile, x));
}
function from_candid_vec_n48(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItem>): Array<MenuItem> {
    return value.map((x)=>from_candid_MenuItem_n49(uploadFile, downloadFile, x));
}
function from_candid_vec_n51(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, Array<_MenuItem>]>): Array<[string, Array<MenuItem>]> {
    return value.map((x)=>from_candid_tuple_n52(uploadFile, downloadFile, x));
}
function to_candid_Currency_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Currency): _Currency {
    return to_candid_variant_n14(uploadFile, downloadFile, value);
}
function to_candid_EmployeeCategory_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeCategory): _EmployeeCategory {
    return to_candid_variant_n4(uploadFile, downloadFile, value);
}
function to_candid_EmployeeRole_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeRole): _EmployeeRole {
    return to_candid_variant_n4(uploadFile, downloadFile, value);
}
function to_candid_Employee_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Employee): _Employee {
    return to_candid_record_n2(uploadFile, downloadFile, value);
}
function to_candid_MenuItem_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuItem): _MenuItem {
    return to_candid_record_n6(uploadFile, downloadFile, value);
}
function to_candid_OrderBatch_n59(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderBatch): _OrderBatch {
    return to_candid_record_n60(uploadFile, downloadFile, value);
}
function to_candid_OrderItem_n62(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderItem): _OrderItem {
    return to_candid_record_n63(uploadFile, downloadFile, value);
}
function to_candid_OrderSource_n54(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderSource): _OrderSource {
    return to_candid_variant_n55(uploadFile, downloadFile, value);
}
function to_candid_OrderStatus_n56(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n57(uploadFile, downloadFile, value);
}
function to_candid_Restaurant_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Restaurant): _Restaurant {
    return to_candid_record_n12(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid_opt_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestaurantId | null): [] | [_RestaurantId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeId | null): [] | [_EmployeeId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: RestaurantId;
    manager: Principal;
    name: string;
    components: Array<Component>;
    description: string;
    tables: Array<Table>;
    address: string;
    defaultCurrency: Currency;
    identityId: RestaurantIdentityId;
    colorScheme: ColorScheme;
}): {
    id: _RestaurantId;
    manager: Principal;
    name: string;
    components: Array<_Component>;
    description: string;
    tables: Array<_Table>;
    address: string;
    defaultCurrency: _Currency;
    identityId: _RestaurantIdentityId;
    colorScheme: _ColorScheme;
} {
    return {
        id: value.id,
        manager: value.manager,
        name: value.name,
        components: value.components,
        description: value.description,
        tables: value.tables,
        address: value.address,
        defaultCurrency: to_candid_Currency_n13(uploadFile, downloadFile, value.defaultCurrency),
        identityId: value.identityId,
        colorScheme: value.colorScheme
    };
}
function to_candid_record_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: EmployeeId;
    principal?: Principal;
    name: string;
    role: EmployeeRole;
    accessCode: AccessCode;
}): {
    id: _EmployeeId;
    principal: [] | [Principal];
    name: string;
    role: _EmployeeRole;
    accessCode: _AccessCode;
} {
    return {
        id: value.id,
        principal: value.principal ? candid_some(value.principal) : candid_none(),
        name: value.name,
        role: to_candid_EmployeeRole_n3(uploadFile, downloadFile, value.role),
        accessCode: value.accessCode
    };
}
function to_candid_record_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: MenuItemId;
    name: string;
    routedBy: EmployeeCategory;
    description: string;
    componentId: ComponentId;
    category: string;
    price: bigint;
}): {
    id: _MenuItemId;
    name: string;
    routedBy: _EmployeeCategory;
    description: string;
    componentId: _ComponentId;
    category: string;
    price: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        routedBy: to_candid_EmployeeCategory_n7(uploadFile, downloadFile, value.routedBy),
        description: value.description,
        componentId: value.componentId,
        category: value.category,
        price: value.price
    };
}
function to_candid_record_n60(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: OrderId;
    status: OrderStatus;
    source: OrderSource;
    toLabel: string;
    tableId: TableId;
    restaurantId: RestaurantId;
    currency: Currency;
    timestamp: bigint;
    customerId?: Principal;
    items: Array<OrderItem>;
}): {
    id: _OrderId;
    status: _OrderStatus;
    source: _OrderSource;
    toLabel: string;
    tableId: _TableId;
    restaurantId: _RestaurantId;
    currency: _Currency;
    timestamp: bigint;
    customerId: [] | [Principal];
    items: Array<_OrderItem>;
} {
    return {
        id: value.id,
        status: to_candid_OrderStatus_n56(uploadFile, downloadFile, value.status),
        source: to_candid_OrderSource_n54(uploadFile, downloadFile, value.source),
        toLabel: value.toLabel,
        tableId: value.tableId,
        restaurantId: value.restaurantId,
        currency: to_candid_Currency_n13(uploadFile, downloadFile, value.currency),
        timestamp: value.timestamp,
        customerId: value.customerId ? candid_some(value.customerId) : candid_none(),
        items: to_candid_vec_n61(uploadFile, downloadFile, value.items)
    };
}
function to_candid_record_n63(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    componentId: ComponentId;
    quantity: bigint;
    category: EmployeeCategory;
    menuItemId: MenuItemId;
}): {
    componentId: _ComponentId;
    quantity: bigint;
    category: _EmployeeCategory;
    menuItemId: _MenuItemId;
} {
    return {
        componentId: value.componentId,
        quantity: value.quantity,
        category: to_candid_EmployeeCategory_n7(uploadFile, downloadFile, value.category),
        menuItemId: value.menuItemId
    };
}
function to_candid_variant_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Currency): {
    eur: null;
} | {
    usd: null;
} {
    return value == Currency.eur ? {
        eur: null
    } : value == Currency.usd ? {
        usd: null
    } : value;
}
function to_candid_variant_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeRole): {
    bar: null;
} | {
    kitchen: null;
} | {
    waiter: null;
} {
    return value == EmployeeRole.bar ? {
        bar: null
    } : value == EmployeeRole.kitchen ? {
        kitchen: null
    } : value == EmployeeRole.waiter ? {
        waiter: null
    } : value;
}
function to_candid_variant_n55(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderSource): {
    bar: null;
} | {
    table: null;
} | {
    kitchen: null;
} {
    return value == OrderSource.bar ? {
        bar: null
    } : value == OrderSource.table ? {
        table: null
    } : value == OrderSource.kitchen ? {
        kitchen: null
    } : value;
}
function to_candid_variant_n57(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    paid: null;
} | {
    ordered: null;
} | {
    readyToServe: null;
} | {
    toBePaid: null;
} {
    return value == OrderStatus.paid ? {
        paid: null
    } : value == OrderStatus.ordered ? {
        ordered: null
    } : value == OrderStatus.readyToServe ? {
        readyToServe: null
    } : value == OrderStatus.toBePaid ? {
        toBePaid: null
    } : value;
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n61(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<OrderItem>): Array<_OrderItem> {
    return value.map((x)=>to_candid_OrderItem_n62(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}