/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccessCode = string;
export interface AccessCodeData {
  'expiresAt' : [] | [bigint],
  'code' : AccessCode,
  'createdAt' : bigint,
  'role' : UserRole,
  'isActive' : boolean,
  'restaurantId' : [] | [RestaurantId],
  'employeeId' : [] | [EmployeeId],
}
export type CanisterId = string;
export interface ColorScheme {
  'primaryColor' : string,
  'accentColor' : string,
  'secondaryColor' : string,
}
export interface Component {
  'id' : ComponentId,
  'name' : string,
  'description' : string,
}
export type ComponentId = string;
export type Currency = { 'eur' : null } |
  { 'usd' : null };
export interface Employee {
  'id' : EmployeeId,
  'principal' : [] | [Principal],
  'name' : string,
  'role' : EmployeeRole,
  'accessCode' : AccessCode,
}
export type EmployeeCategory = { 'bar' : null } |
  { 'kitchen' : null } |
  { 'waiter' : null };
export type EmployeeId = string;
export type EmployeeRole = { 'bar' : null } |
  { 'kitchen' : null } |
  { 'waiter' : null };
export interface ExchangeRate { 'usdToEur' : number, 'eurToUsd' : number }
export interface MenuItem {
  'id' : MenuItemId,
  'name' : string,
  'routedBy' : EmployeeCategory,
  'description' : string,
  'componentId' : ComponentId,
  'category' : string,
  'price' : bigint,
}
export type MenuItemId = string;
export interface OrderBatch {
  'id' : OrderId,
  'status' : OrderStatus,
  'source' : OrderSource,
  'toLabel' : string,
  'tableId' : TableId,
  'restaurantId' : RestaurantId,
  'currency' : Currency,
  'timestamp' : bigint,
  'customerId' : [] | [Principal],
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'componentId' : ComponentId,
  'quantity' : bigint,
  'category' : EmployeeCategory,
  'menuItemId' : MenuItemId,
}
export type OrderSource = { 'bar' : null } |
  { 'table' : null } |
  { 'kitchen' : null };
export type OrderStatus = { 'paid' : null } |
  { 'ordered' : null } |
  { 'readyToServe' : null } |
  { 'toBePaid' : null };
export interface Restaurant {
  'id' : RestaurantId,
  'manager' : Principal,
  'name' : string,
  'components' : Array<Component>,
  'description' : string,
  'tables' : Array<Table>,
  'address' : string,
  'defaultCurrency' : Currency,
  'identityId' : RestaurantIdentityId,
  'colorScheme' : ColorScheme,
}
export type RestaurantId = string;
export type RestaurantIdentityId = string;
export interface Table {
  'id' : TableId,
  'customerLink' : string,
  'active' : boolean,
  'name' : string,
  'location' : string,
}
export type TableId = string;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'addEmployee' : ActorMethod<[RestaurantId, Employee], undefined>,
  'addMenuItem' : ActorMethod<[RestaurantId, MenuItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRestaurantToCanister' : ActorMethod<
    [RestaurantId, CanisterId],
    undefined
  >,
  'checkEmployeeLink' : ActorMethod<
    [Principal, RestaurantIdentityId],
    [] | [EmployeeId]
  >,
  'claimAccessCode' : ActorMethod<
    [AccessCode, RestaurantIdentityId],
    undefined
  >,
  'createRestaurant' : ActorMethod<[Restaurant], undefined>,
  'deactivateAccessCode' : ActorMethod<[AccessCode], undefined>,
  'deleteEmployee' : ActorMethod<[RestaurantId, EmployeeId], undefined>,
  'deleteMenuItem' : ActorMethod<[RestaurantId, MenuItemId], undefined>,
  'deleteTable' : ActorMethod<[RestaurantId, TableId], undefined>,
  'generateAccessCode' : ActorMethod<
    [UserRole, [] | [RestaurantId], [] | [EmployeeId]],
    AccessCode
  >,
  'getAccessCodesByRestaurant' : ActorMethod<
    [RestaurantId],
    Array<AccessCodeData>
  >,
  'getAllRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'getAvailableAccessCodes' : ActorMethod<
    [RestaurantIdentityId],
    Array<AccessCode>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCanisterForRestaurant' : ActorMethod<[RestaurantId], [] | [CanisterId]>,
  'getCustomerOrderHistory' : ActorMethod<[], Array<OrderBatch>>,
  'getEmployees' : ActorMethod<[RestaurantId], Array<Employee>>,
  'getExchangeRate' : ActorMethod<[], ExchangeRate>,
  'getMenuItems' : ActorMethod<[RestaurantId], Array<MenuItem>>,
  'getMenuItemsByCategory' : ActorMethod<
    [RestaurantId],
    Array<[string, Array<MenuItem>]>
  >,
  'getOrder' : ActorMethod<[OrderId], [] | [OrderBatch]>,
  'getOrdersBySource' : ActorMethod<
    [RestaurantId, OrderSource],
    Array<OrderBatch>
  >,
  'getOrdersByStatus' : ActorMethod<
    [RestaurantId, OrderStatus],
    Array<OrderBatch>
  >,
  'getOrdersByStatusAndSource' : ActorMethod<
    [RestaurantId, OrderStatus, OrderSource],
    Array<OrderBatch>
  >,
  'getOrdersForRestaurant' : ActorMethod<[RestaurantId], Array<OrderBatch>>,
  'getOrdersForWaiter' : ActorMethod<[RestaurantId], Array<OrderBatch>>,
  'getRestaurant' : ActorMethod<[RestaurantId], [] | [Restaurant]>,
  'getRestaurantByTableId' : ActorMethod<[TableId], [] | [Restaurant]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getValidAccessCodesForRestaurant' : ActorMethod<
    [RestaurantId],
    Array<AccessCodeData>
  >,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[OrderBatch], OrderId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCustomAccessCode' : ActorMethod<
    [RestaurantId, EmployeeId, AccessCode],
    undefined
  >,
  'updateAccessCode' : ActorMethod<[AccessCode], AccessCode>,
  'updateExchangeRate' : ActorMethod<[ExchangeRate], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateRestaurant' : ActorMethod<[Restaurant], undefined>,
  'validateRestaurantIdentityId' : ActorMethod<[RestaurantIdentityId], boolean>,
  'verifyAccessCode' : ActorMethod<
    [AccessCode],
    {
      'role' : [] | [UserRole],
      'error' : string,
      'restaurantId' : [] | [RestaurantId],
      'employeeId' : [] | [EmployeeId],
      'isValid' : boolean,
    }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];